### ISSUE TITLE
Bug with file upload on firefox.

### ISSUE THREAD

**Issue by gmagnenat** [zero-to-mastery/visual-music#5]
On development branch.
The file upload is not working on Firefox. It fires a "No file loaded" alert.
It works without problems on Chrome.
![Capture d’écran 2019-07-22 à 10 21 11](https://user-images.githubusercontent.com/924127/61617201-82a6ef80-ac6a-11e9-8299-a6bc23cdc660.png)

**Comment by ecdunan** [comment]
Hi, thanks for reporting this. It seems to be caused by a check that I added to ensure that only mp3 files will be loaded. I'll issue a PR to fix this shortly. Thanks again :D

**Comment by gmagnenat** [comment]
Thank you for the quick fix. I just tested again on Firefox. It seems to work as expected on Firefox but there is still a small glitch. Maybe you have an idea how to quickly fix that?
On first load, when I select a file and click **play**, it doesn't play. It needs one extra interaction : click on the volume or click on pause/play to play the track.
